[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  # SPA fallback - serve index.html for all routes
  from = "/*"
  to = "/index.html"
  status = 200 