[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  # Cache static assets
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  # Static assets should be served directly
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = false

[[redirects]]
  # SPA fallback for all other routes
  from = "/*"
  to = "/index.html"
  status = 200 