export const banks = {
  '001': 'Central Bank of Nigeria',
  '011': 'First Bank of Nigeria',
  '014': 'Afribank Nigeria',
  '023': 'Citibank Nigeria',
  '030': 'Heritage Bank',
  '032': 'Union Bank of Nigeria',
  '033': 'United Bank for Africa',
  '044': 'Access Bank',
  '050': 'Ecobank Nigeria',
  '057': 'Zenith Bank',
  '058': 'Guaranty Trust Bank',
  '070': 'Fidelity Bank',
  '076': 'Skye Bank',
  '082': 'Keystone Bank',
  '084': 'Enterprise Bank',
  '221': 'Stanbic IBTC Bank',
  '232': 'Sterling Bank',
  '215': 'Unity Bank',
  '214': 'First City Monument Bank',
} 